### ISSUE TITLE
CUDA out of memory， finetune on customer data, what GPU you used to train?

### ISSUE THREAD

**Issue by yuwProject** [JayParanjape/F-ViTA#8]
Thanks for you great work!
I try to finetune on my own data. 

![Image](https://github.com/user-attachments/assets/b5ec586c-8e95-4e29-a3a1-e316cf4b5521)

batch size set as 1. always get this error. 

![Image](https://github.com/user-attachments/assets/8e99e20a-4b03-42d7-9adb-f87d9d8466db)

Any suggestions ? Many thanks in advance!

**Comment by xzhichaox** [comment]
I have also encountered the same problem. Have you solved it? How did you solve it?

**Comment by zhanglang1860** [comment]
> I have also encountered the same problem. Have you solved it? How did you solve it?

for train, I change script:
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1

export MODEL_ID="./instruct-pix2pix"
export DATASET_ID="train_data"   
export OUTPUT_DIR="./F-VITA_weights/train"
 
CUDA_VISIBLE_DEVICES=0 \
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True accelerate launch --num_processes 1 --mixed_precision="fp16" finetune_instruct_pix2pix.py \
  --pretrained_model_name_or_path=$MODEL_ID \
  --dataset_name=$DATASET_ID \
  --use_ema \
  --resolution=256 --random_flip \
  --train_batch_size=1 --gradient_accumulation_steps=4 --gradient_checkpointing \
  --max_train_steps=80000 \
  --checkpointing_steps=20000 --checkpoints_total_limit=20 \
  --learning_rate=5e-05 --lr_warmup_steps=0 \
  --mixed_precision=fp16 \
  --seed=42 \
  --original_image_column="visible_image" \
  --edit_prompt_column="edit_instruction" \
  --edited_image_column="thermal_image" \
  --output_dir=$OUTPUT_DIR \
  --use_ibl=False \
  --use_extra_mse=False \
  --use_masks=True \
  --use_boxes=False \
  --use_text=True  \
  --use_8bit_adam  # MUST


for test:
export PYTHONPATH=$PYTHONPATH:/home/user/segment-anything-2
CUDA_VISIBLE_DEVICES=0 python3 inference_gsam.py './F-VITA_weights/train' './F-VITA_output' 'RGB_data'

**Comment by xzhichaox** [comment]
Thank you very much, this issue has been resolved
